/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait AssetsApi: Send + Sync {
    /// GET /assets
    ///
    ///
    async fn assets_get<
        'state,
        'media_type,
        'tags,
        'has_proxy,
        'tags_mode,
        'q,
        'location_country,
        'location_city,
        'geo_bbox,
        'sort,
        'limit,
        'cursor,
    >(
        &self,
        state: Option<models::AssetState>,
        media_type: Option<&'media_type str>,
        tags: Option<&'tags str>,
        has_proxy: Option<bool>,
        tags_mode: Option<&'tags_mode str>,
        q: Option<&'q str>,
        location_country: Option<&'location_country str>,
        location_city: Option<&'location_city str>,
        geo_bbox: Option<&'geo_bbox str>,
        sort: Option<&'sort str>,
        limit: Option<i32>,
        cursor: Option<&'cursor str>,
    ) -> Result<models::AssetsGet200Response, Error<AssetsGetError>>;

    /// GET /assets/{uuid}
    ///
    ///
    async fn assets_uuid_get<'uuid>(
        &self,
        uuid: &'uuid str,
    ) -> Result<models::AssetDetail, Error<AssetsUuidGetError>>;

    /// PATCH /assets/{uuid}
    ///
    ///
    async fn assets_uuid_patch<'uuid, 'assets_uuid_patch_request>(
        &self,
        uuid: &'uuid str,
        assets_uuid_patch_request: models::AssetsUuidPatchRequest,
    ) -> Result<(), Error<AssetsUuidPatchError>>;

    /// POST /assets/{uuid}/reprocess
    ///
    ///
    async fn assets_uuid_reprocess_post<'uuid, 'idempotency_key>(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
    ) -> Result<(), Error<AssetsUuidReprocessPostError>>;
}

pub struct AssetsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl AssetsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl AssetsApi for AssetsApiClient {
    async fn assets_get<
        'state,
        'media_type,
        'tags,
        'has_proxy,
        'tags_mode,
        'q,
        'location_country,
        'location_city,
        'geo_bbox,
        'sort,
        'limit,
        'cursor,
    >(
        &self,
        state: Option<models::AssetState>,
        media_type: Option<&'media_type str>,
        tags: Option<&'tags str>,
        has_proxy: Option<bool>,
        tags_mode: Option<&'tags_mode str>,
        q: Option<&'q str>,
        location_country: Option<&'location_country str>,
        location_city: Option<&'location_city str>,
        geo_bbox: Option<&'geo_bbox str>,
        sort: Option<&'sort str>,
        limit: Option<i32>,
        cursor: Option<&'cursor str>,
    ) -> Result<models::AssetsGet200Response, Error<AssetsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/assets", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = state {
            local_var_req_builder =
                local_var_req_builder.query(&[("state", &param_value.to_string())]);
        }
        if let Some(ref param_value) = media_type {
            local_var_req_builder =
                local_var_req_builder.query(&[("media_type", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tags {
            local_var_req_builder =
                local_var_req_builder.query(&[("tags", &param_value.to_string())]);
        }
        if let Some(ref param_value) = has_proxy {
            local_var_req_builder =
                local_var_req_builder.query(&[("has_proxy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tags_mode {
            local_var_req_builder =
                local_var_req_builder.query(&[("tags_mode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = q {
            local_var_req_builder = local_var_req_builder.query(&[("q", &param_value.to_string())]);
        }
        if let Some(ref param_value) = location_country {
            local_var_req_builder =
                local_var_req_builder.query(&[("location_country", &param_value.to_string())]);
        }
        if let Some(ref param_value) = location_city {
            local_var_req_builder =
                local_var_req_builder.query(&[("location_city", &param_value.to_string())]);
        }
        if let Some(ref param_value) = geo_bbox {
            local_var_req_builder =
                local_var_req_builder.query(&[("geo_bbox", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("cursor", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AssetsGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AssetsGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<AssetsGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_get<'uuid>(
        &self,
        uuid: &'uuid str,
    ) -> Result<models::AssetDetail, Error<AssetsUuidGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AssetDetail`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AssetDetail`")))),
            }
        } else {
            let local_var_entity: Option<AssetsUuidGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_patch<'uuid, 'assets_uuid_patch_request>(
        &self,
        uuid: &'uuid str,
        assets_uuid_patch_request: models::AssetsUuidPatchRequest,
    ) -> Result<(), Error<AssetsUuidPatchError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&assets_uuid_patch_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidPatchError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_reprocess_post<'uuid, 'idempotency_key>(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
    ) -> Result<(), Error<AssetsUuidReprocessPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/reprocess",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidReprocessPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`AssetsApi::assets_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssetsApi::assets_uuid_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssetsApi::assets_uuid_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidPatchError {
    Status410(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssetsApi::assets_uuid_reprocess_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidReprocessPostError {
    Status409(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}
