/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait DecisionsApi: Send + Sync {
    /// POST /assets/{uuid}/decision
    ///
    ///
    async fn assets_uuid_decision_post<
        'uuid,
        'idempotency_key,
        'assets_uuid_decision_post_request,
    >(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
        assets_uuid_decision_post_request: models::AssetsUuidDecisionPostRequest,
    ) -> Result<(), Error<AssetsUuidDecisionPostError>>;

    /// POST /assets/{uuid}/reopen
    ///
    ///
    async fn assets_uuid_reopen_post<'uuid>(
        &self,
        uuid: &'uuid str,
    ) -> Result<(), Error<AssetsUuidReopenPostError>>;

    /// POST /decisions/apply
    ///
    /// Available in v1.1+ when `features.decisions.bulk=true`.
    async fn decisions_apply_post<'idempotency_key, 'decisions_apply_post_request>(
        &self,
        idempotency_key: &'idempotency_key str,
        decisions_apply_post_request: models::DecisionsApplyPostRequest,
    ) -> Result<(), Error<DecisionsApplyPostError>>;

    /// POST /decisions/preview
    ///
    /// Available in v1.1+ when `features.decisions.bulk=true`.
    async fn decisions_preview_post<'decisions_preview_post_request>(
        &self,
        decisions_preview_post_request: models::DecisionsPreviewPostRequest,
    ) -> Result<(), Error<DecisionsPreviewPostError>>;
}

pub struct DecisionsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl DecisionsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl DecisionsApi for DecisionsApiClient {
    async fn assets_uuid_decision_post<
        'uuid,
        'idempotency_key,
        'assets_uuid_decision_post_request,
    >(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
        assets_uuid_decision_post_request: models::AssetsUuidDecisionPostRequest,
    ) -> Result<(), Error<AssetsUuidDecisionPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/decision",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&assets_uuid_decision_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidDecisionPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_reopen_post<'uuid>(
        &self,
        uuid: &'uuid str,
    ) -> Result<(), Error<AssetsUuidReopenPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/reopen",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidReopenPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Available in v1.1+ when `features.decisions.bulk=true`.
    async fn decisions_apply_post<'idempotency_key, 'decisions_apply_post_request>(
        &self,
        idempotency_key: &'idempotency_key str,
        decisions_apply_post_request: models::DecisionsApplyPostRequest,
    ) -> Result<(), Error<DecisionsApplyPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/decisions/apply", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&decisions_apply_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DecisionsApplyPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Available in v1.1+ when `features.decisions.bulk=true`.
    async fn decisions_preview_post<'decisions_preview_post_request>(
        &self,
        decisions_preview_post_request: models::DecisionsPreviewPostRequest,
    ) -> Result<(), Error<DecisionsPreviewPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/decisions/preview", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&decisions_preview_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DecisionsPreviewPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`DecisionsApi::assets_uuid_decision_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidDecisionPostError {
    Status409(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DecisionsApi::assets_uuid_reopen_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidReopenPostError {
    Status409(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DecisionsApi::decisions_apply_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DecisionsApplyPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DecisionsApi::decisions_preview_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DecisionsPreviewPostError {
    UnknownValue(serde_json::Value),
}
