/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait DerivedApi: Send + Sync {
    /// GET /assets/{uuid}/derived
    ///
    ///
    async fn assets_uuid_derived_get<'uuid>(
        &self,
        uuid: &'uuid str,
    ) -> Result<
        std::collections::HashMap<String, serde_json::Value>,
        Error<AssetsUuidDerivedGetError>,
    >;

    /// GET /assets/{uuid}/derived/{kind}
    ///
    ///
    async fn assets_uuid_derived_kind_get<'uuid, 'kind>(
        &self,
        uuid: &'uuid str,
        kind: &'kind str,
    ) -> Result<(), Error<AssetsUuidDerivedKindGetError>>;

    /// POST /assets/{uuid}/derived/upload/complete
    ///
    ///
    async fn assets_uuid_derived_upload_complete_post<
        'uuid,
        'idempotency_key,
        'assets_uuid_derived_upload_complete_post_request,
    >(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
        assets_uuid_derived_upload_complete_post_request: models::AssetsUuidDerivedUploadCompletePostRequest,
    ) -> Result<(), Error<AssetsUuidDerivedUploadCompletePostError>>;

    /// POST /assets/{uuid}/derived/upload/init
    ///
    ///
    async fn assets_uuid_derived_upload_init_post<
        'uuid,
        'idempotency_key,
        'assets_uuid_derived_upload_init_post_request,
    >(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
        assets_uuid_derived_upload_init_post_request: models::AssetsUuidDerivedUploadInitPostRequest,
    ) -> Result<(), Error<AssetsUuidDerivedUploadInitPostError>>;

    /// POST /assets/{uuid}/derived/upload/part
    ///
    ///
    async fn assets_uuid_derived_upload_part_post<
        'uuid,
        'assets_uuid_derived_upload_part_post_request,
    >(
        &self,
        uuid: &'uuid str,
        assets_uuid_derived_upload_part_post_request: models::AssetsUuidDerivedUploadPartPostRequest,
    ) -> Result<(), Error<AssetsUuidDerivedUploadPartPostError>>;
}

pub struct DerivedApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl DerivedApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl DerivedApi for DerivedApiClient {
    async fn assets_uuid_derived_get<'uuid>(
        &self,
        uuid: &'uuid str,
    ) -> Result<
        std::collections::HashMap<String, serde_json::Value>,
        Error<AssetsUuidDerivedGetError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/derived",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`")))),
            }
        } else {
            let local_var_entity: Option<AssetsUuidDerivedGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_derived_kind_get<'uuid, 'kind>(
        &self,
        uuid: &'uuid str,
        kind: &'kind str,
    ) -> Result<(), Error<AssetsUuidDerivedKindGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/derived/{kind}",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid),
            kind = crate::apis::urlencode(kind)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidDerivedKindGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_derived_upload_complete_post<
        'uuid,
        'idempotency_key,
        'assets_uuid_derived_upload_complete_post_request,
    >(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
        assets_uuid_derived_upload_complete_post_request: models::AssetsUuidDerivedUploadCompletePostRequest,
    ) -> Result<(), Error<AssetsUuidDerivedUploadCompletePostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/derived/upload/complete",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&assets_uuid_derived_upload_complete_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidDerivedUploadCompletePostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_derived_upload_init_post<
        'uuid,
        'idempotency_key,
        'assets_uuid_derived_upload_init_post_request,
    >(
        &self,
        uuid: &'uuid str,
        idempotency_key: &'idempotency_key str,
        assets_uuid_derived_upload_init_post_request: models::AssetsUuidDerivedUploadInitPostRequest,
    ) -> Result<(), Error<AssetsUuidDerivedUploadInitPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/derived/upload/init",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&assets_uuid_derived_upload_init_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidDerivedUploadInitPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn assets_uuid_derived_upload_part_post<
        'uuid,
        'assets_uuid_derived_upload_part_post_request,
    >(
        &self,
        uuid: &'uuid str,
        assets_uuid_derived_upload_part_post_request: models::AssetsUuidDerivedUploadPartPostRequest,
    ) -> Result<(), Error<AssetsUuidDerivedUploadPartPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/assets/{uuid}/derived/upload/part",
            local_var_configuration.base_path,
            uuid = crate::apis::urlencode(uuid)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&assets_uuid_derived_upload_part_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AssetsUuidDerivedUploadPartPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`DerivedApi::assets_uuid_derived_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidDerivedGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DerivedApi::assets_uuid_derived_kind_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidDerivedKindGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DerivedApi::assets_uuid_derived_upload_complete_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidDerivedUploadCompletePostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DerivedApi::assets_uuid_derived_upload_init_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidDerivedUploadInitPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DerivedApi::assets_uuid_derived_upload_part_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetsUuidDerivedUploadPartPostError {
    UnknownValue(serde_json::Value),
}
