/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait JobsApi: Send + Sync {

    /// GET /jobs
    ///
    /// Returns jobs with status `pending` and compatible with the agent capabilities. 
    async fn jobs_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<Vec<models::Job>, Error<JobsGetError>>;

    /// POST /jobs/{job_id}/claim
    ///
    /// 
    async fn jobs_job_id_claim_post<'job_id, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'accept_language>(&self, job_id: &'job_id str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, accept_language: Option<&'accept_language str>) -> Result<models::Job, Error<JobsJobIdClaimPostError>>;

    /// POST /jobs/{job_id}/fail
    ///
    /// 
    async fn jobs_job_id_fail_post<'job_id, 'idempotency_key, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'jobs_job_id_fail_post_request, 'accept_language>(&self, job_id: &'job_id str, idempotency_key: &'idempotency_key str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, jobs_job_id_fail_post_request: models::JobsJobIdFailPostRequest, accept_language: Option<&'accept_language str>) -> Result<(), Error<JobsJobIdFailPostError>>;

    /// POST /jobs/{job_id}/heartbeat
    ///
    /// 
    async fn jobs_job_id_heartbeat_post<'job_id, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'jobs_job_id_heartbeat_post_request, 'accept_language>(&self, job_id: &'job_id str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, jobs_job_id_heartbeat_post_request: models::JobsJobIdHeartbeatPostRequest, accept_language: Option<&'accept_language str>) -> Result<models::JobsJobIdHeartbeatPost200Response, Error<JobsJobIdHeartbeatPostError>>;

    /// POST /jobs/{job_id}/submit
    ///
    /// Submits one job result patch. 
    async fn jobs_job_id_submit_post<'job_id, 'idempotency_key, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'job_submit_request, 'accept_language>(&self, job_id: &'job_id str, idempotency_key: &'idempotency_key str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, job_submit_request: models::JobSubmitRequest, accept_language: Option<&'accept_language str>) -> Result<(), Error<JobsJobIdSubmitPostError>>;
}

pub struct JobsApiClient {
    configuration: Arc<configuration::Configuration>
}

impl JobsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl JobsApi for JobsApiClient {
    /// Returns jobs with status `pending` and compatible with the agent capabilities. 
    async fn jobs_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<Vec<models::Job>, Error<JobsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/jobs", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Job&gt;`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::Job&gt;`")))),
            }
        } else {
            let local_var_entity: Option<JobsGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn jobs_job_id_claim_post<'job_id, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'accept_language>(&self, job_id: &'job_id str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, accept_language: Option<&'accept_language str>) -> Result<models::Job, Error<JobsJobIdClaimPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/jobs/{job_id}/claim", local_var_configuration.base_path, job_id=crate::apis::urlencode(job_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Agent-Id", x_retaia_agent_id.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-OpenPGP-Fingerprint", x_retaia_open_pgp_fingerprint.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature", x_retaia_signature.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Timestamp", x_retaia_signature_timestamp.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Nonce", x_retaia_signature_nonce.to_string());
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Job`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Job`")))),
            }
        } else {
            let local_var_entity: Option<JobsJobIdClaimPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn jobs_job_id_fail_post<'job_id, 'idempotency_key, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'jobs_job_id_fail_post_request, 'accept_language>(&self, job_id: &'job_id str, idempotency_key: &'idempotency_key str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, jobs_job_id_fail_post_request: models::JobsJobIdFailPostRequest, accept_language: Option<&'accept_language str>) -> Result<(), Error<JobsJobIdFailPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/jobs/{job_id}/fail", local_var_configuration.base_path, job_id=crate::apis::urlencode(job_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Agent-Id", x_retaia_agent_id.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-OpenPGP-Fingerprint", x_retaia_open_pgp_fingerprint.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature", x_retaia_signature.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Timestamp", x_retaia_signature_timestamp.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Nonce", x_retaia_signature_nonce.to_string());
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&jobs_job_id_fail_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<JobsJobIdFailPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn jobs_job_id_heartbeat_post<'job_id, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'jobs_job_id_heartbeat_post_request, 'accept_language>(&self, job_id: &'job_id str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, jobs_job_id_heartbeat_post_request: models::JobsJobIdHeartbeatPostRequest, accept_language: Option<&'accept_language str>) -> Result<models::JobsJobIdHeartbeatPost200Response, Error<JobsJobIdHeartbeatPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/jobs/{job_id}/heartbeat", local_var_configuration.base_path, job_id=crate::apis::urlencode(job_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Agent-Id", x_retaia_agent_id.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-OpenPGP-Fingerprint", x_retaia_open_pgp_fingerprint.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature", x_retaia_signature.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Timestamp", x_retaia_signature_timestamp.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Nonce", x_retaia_signature_nonce.to_string());
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&jobs_job_id_heartbeat_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::JobsJobIdHeartbeatPost200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::JobsJobIdHeartbeatPost200Response`")))),
            }
        } else {
            let local_var_entity: Option<JobsJobIdHeartbeatPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Submits one job result patch. 
    async fn jobs_job_id_submit_post<'job_id, 'idempotency_key, 'x_retaia_agent_id, 'x_retaia_open_pgp_fingerprint, 'x_retaia_signature, 'x_retaia_signature_timestamp, 'x_retaia_signature_nonce, 'job_submit_request, 'accept_language>(&self, job_id: &'job_id str, idempotency_key: &'idempotency_key str, x_retaia_agent_id: &str, x_retaia_open_pgp_fingerprint: &'x_retaia_open_pgp_fingerprint str, x_retaia_signature: &'x_retaia_signature str, x_retaia_signature_timestamp: String, x_retaia_signature_nonce: &'x_retaia_signature_nonce str, job_submit_request: models::JobSubmitRequest, accept_language: Option<&'accept_language str>) -> Result<(), Error<JobsJobIdSubmitPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/jobs/{job_id}/submit", local_var_configuration.base_path, job_id=crate::apis::urlencode(job_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.header("Idempotency-Key", idempotency_key.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Agent-Id", x_retaia_agent_id.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-OpenPGP-Fingerprint", x_retaia_open_pgp_fingerprint.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature", x_retaia_signature.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Timestamp", x_retaia_signature_timestamp.to_string());
        local_var_req_builder = local_var_req_builder.header("X-Retaia-Signature-Nonce", x_retaia_signature_nonce.to_string());
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&job_submit_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<JobsJobIdSubmitPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`JobsApi::jobs_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobsGetError {
    Status401(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`JobsApi::jobs_job_id_claim_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobsJobIdClaimPostError {
    Status401(models::ErrorResponse),
    Status409(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`JobsApi::jobs_job_id_fail_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobsJobIdFailPostError {
    Status401(models::ErrorResponse),
    Status409(models::ErrorResponse),
    Status423(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`JobsApi::jobs_job_id_heartbeat_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobsJobIdHeartbeatPostError {
    Status401(models::ErrorResponse),
    Status409(models::ErrorResponse),
    Status423(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`JobsApi::jobs_job_id_submit_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobsJobIdSubmitPostError {
    Status401(models::ErrorResponse),
    Status409(models::ErrorResponse),
    Status423(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

