/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait OpsApi: Send + Sync {

    /// GET /ops/agents
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_agents_get<'status, 'limit, 'offset, 'accept_language>(&self, status: Option<&'status str>, limit: Option<i32>, offset: Option<i32>, accept_language: Option<&'accept_language str>) -> Result<models::OpsAgentsGet200Response, Error<OpsAgentsGetError>>;

    /// GET /ops/ingest/diagnostics
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_ingest_diagnostics_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<models::OpsIngestDiagnosticsGet200Response, Error<OpsIngestDiagnosticsGetError>>;

    /// POST /ops/ingest/requeue
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_ingest_requeue_post<'ops_ingest_requeue_post_request, 'accept_language>(&self, ops_ingest_requeue_post_request: Option<models::OpsIngestRequeuePostRequest>, accept_language: Option<&'accept_language str>) -> Result<models::OpsIngestRequeuePost202Response, Error<OpsIngestRequeuePostError>>;

    /// GET /ops/ingest/unmatched
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_ingest_unmatched_get<'reason, 'since, 'limit, 'accept_language>(&self, reason: Option<&'reason str>, since: Option<String>, limit: Option<i32>, accept_language: Option<&'accept_language str>) -> Result<models::OpsIngestUnmatchedGet200Response, Error<OpsIngestUnmatchedGetError>>;

    /// GET /ops/jobs/queue
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_jobs_queue_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<models::OpsJobsQueueGet200Response, Error<OpsJobsQueueGetError>>;

    /// GET /ops/locks
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_locks_get<'asset_uuid, 'lock_type, 'limit, 'offset, 'accept_language>(&self, asset_uuid: Option<&'asset_uuid str>, lock_type: Option<&'lock_type str>, limit: Option<i32>, offset: Option<i32>, accept_language: Option<&'accept_language str>) -> Result<models::OpsLocksGet200Response, Error<OpsLocksGetError>>;

    /// POST /ops/locks/recover
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_locks_recover_post<'accept_language, 'ops_locks_recover_post_request>(&self, accept_language: Option<&'accept_language str>, ops_locks_recover_post_request: Option<models::OpsLocksRecoverPostRequest>) -> Result<models::OpsLocksRecoverPost200Response, Error<OpsLocksRecoverPostError>>;

    /// GET /ops/readiness
    ///
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_readiness_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<models::OpsReadinessGet200Response, Error<OpsReadinessGetError>>;
}

pub struct OpsApiClient {
    configuration: Arc<configuration::Configuration>
}

impl OpsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl OpsApi for OpsApiClient {
    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_agents_get<'status, 'limit, 'offset, 'accept_language>(&self, status: Option<&'status str>, limit: Option<i32>, offset: Option<i32>, accept_language: Option<&'accept_language str>) -> Result<models::OpsAgentsGet200Response, Error<OpsAgentsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/agents", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = status {
            local_var_req_builder = local_var_req_builder.query(&[("status", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder = local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder = local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsAgentsGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsAgentsGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsAgentsGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_ingest_diagnostics_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<models::OpsIngestDiagnosticsGet200Response, Error<OpsIngestDiagnosticsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/ingest/diagnostics", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsIngestDiagnosticsGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsIngestDiagnosticsGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsIngestDiagnosticsGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_ingest_requeue_post<'ops_ingest_requeue_post_request, 'accept_language>(&self, ops_ingest_requeue_post_request: Option<models::OpsIngestRequeuePostRequest>, accept_language: Option<&'accept_language str>) -> Result<models::OpsIngestRequeuePost202Response, Error<OpsIngestRequeuePostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/ingest/requeue", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&ops_ingest_requeue_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsIngestRequeuePost202Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsIngestRequeuePost202Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsIngestRequeuePostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_ingest_unmatched_get<'reason, 'since, 'limit, 'accept_language>(&self, reason: Option<&'reason str>, since: Option<String>, limit: Option<i32>, accept_language: Option<&'accept_language str>) -> Result<models::OpsIngestUnmatchedGet200Response, Error<OpsIngestUnmatchedGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/ingest/unmatched", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = reason {
            local_var_req_builder = local_var_req_builder.query(&[("reason", &param_value.to_string())]);
        }
        if let Some(ref param_value) = since {
            local_var_req_builder = local_var_req_builder.query(&[("since", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder = local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsIngestUnmatchedGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsIngestUnmatchedGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsIngestUnmatchedGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_jobs_queue_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<models::OpsJobsQueueGet200Response, Error<OpsJobsQueueGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/jobs/queue", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsJobsQueueGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsJobsQueueGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsJobsQueueGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_locks_get<'asset_uuid, 'lock_type, 'limit, 'offset, 'accept_language>(&self, asset_uuid: Option<&'asset_uuid str>, lock_type: Option<&'lock_type str>, limit: Option<i32>, offset: Option<i32>, accept_language: Option<&'accept_language str>) -> Result<models::OpsLocksGet200Response, Error<OpsLocksGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/locks", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = asset_uuid {
            local_var_req_builder = local_var_req_builder.query(&[("asset_uuid", &param_value.to_string())]);
        }
        if let Some(ref param_value) = lock_type {
            local_var_req_builder = local_var_req_builder.query(&[("lock_type", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder = local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder = local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsLocksGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsLocksGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsLocksGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_locks_recover_post<'accept_language, 'ops_locks_recover_post_request>(&self, accept_language: Option<&'accept_language str>, ops_locks_recover_post_request: Option<models::OpsLocksRecoverPostRequest>) -> Result<models::OpsLocksRecoverPost200Response, Error<OpsLocksRecoverPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/locks/recover", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&ops_locks_recover_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsLocksRecoverPost200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsLocksRecoverPost200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsLocksRecoverPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requires `UserBearerAuth` and an authenticated admin actor, per AUTHZ matrix. 
    async fn ops_readiness_get<'accept_language>(&self, accept_language: Option<&'accept_language str>) -> Result<models::OpsReadinessGet200Response, Error<OpsReadinessGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/ops/readiness", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = accept_language {
            local_var_req_builder = local_var_req_builder.header("Accept-Language", local_var_param_value.to_string());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OpsReadinessGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OpsReadinessGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<OpsReadinessGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`OpsApi::ops_agents_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsAgentsGetError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_ingest_diagnostics_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsIngestDiagnosticsGetError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_ingest_requeue_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsIngestRequeuePostError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_ingest_unmatched_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsIngestUnmatchedGetError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_jobs_queue_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsJobsQueueGetError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_locks_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsLocksGetError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_locks_recover_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsLocksRecoverPostError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OpsApi::ops_readiness_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpsReadinessGetError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

