/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentsRegisterPost200Response {
    #[serde(rename = "agent_id", skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
    #[serde(
        rename = "effective_capabilities",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_capabilities: Option<Vec<String>>,
    #[serde(
        rename = "capability_warnings",
        skip_serializing_if = "Option::is_none"
    )]
    pub capability_warnings: Option<Vec<String>>,
    #[serde(rename = "server_policy", skip_serializing_if = "Option::is_none")]
    pub server_policy: Option<models::ServerPolicy>,
}

impl AgentsRegisterPost200Response {
    pub fn new() -> AgentsRegisterPost200Response {
        AgentsRegisterPost200Response {
            agent_id: None,
            effective_capabilities: None,
            capability_warnings: None,
            server_policy: None,
        }
    }
}
