/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentsRegisterPostRequest {
    #[serde(rename = "agent_name")]
    pub agent_name: String,
    #[serde(rename = "agent_version")]
    pub agent_version: String,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "capabilities")]
    pub capabilities: Vec<String>,
    /// Optional client-advertised feature-flags contract version (SemVer).
    #[serde(
        rename = "client_feature_flags_contract_version",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_feature_flags_contract_version: Option<String>,
    #[serde(rename = "max_parallel_jobs", skip_serializing_if = "Option::is_none")]
    pub max_parallel_jobs: Option<i32>,
}

impl AgentsRegisterPostRequest {
    pub fn new(
        agent_name: String,
        agent_version: String,
        capabilities: Vec<String>,
    ) -> AgentsRegisterPostRequest {
        AgentsRegisterPostRequest {
            agent_name,
            agent_version,
            platform: None,
            capabilities,
            client_feature_flags_contract_version: None,
            max_parallel_jobs: None,
        }
    }
}
