/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentsRegisterPostRequest {
    /// Stable per-agent-instance UUIDv4 generated once and persisted locally by the agent.
    #[serde(rename = "agent_id")]
    pub agent_id: uuid::Uuid,
    #[serde(rename = "agent_name")]
    pub agent_name: String,
    #[serde(rename = "agent_version")]
    pub agent_version: String,
    /// Agent OpenPGP public key in ASCII-armored format.
    #[serde(rename = "openpgp_public_key")]
    pub openpgp_public_key: String,
    /// Canonical OpenPGP fingerprint of the active agent signing key.
    #[serde(rename = "openpgp_fingerprint")]
    pub openpgp_fingerprint: String,
    #[serde(rename = "os_name")]
    pub os_name: OsName,
    #[serde(rename = "os_version")]
    pub os_version: String,
    #[serde(rename = "arch")]
    pub arch: Arch,
    #[serde(rename = "capabilities")]
    pub capabilities: Vec<String>,
    /// Optional client-advertised feature-flags contract version (SemVer).
    #[serde(rename = "client_feature_flags_contract_version", skip_serializing_if = "Option::is_none")]
    pub client_feature_flags_contract_version: Option<String>,
    #[serde(rename = "max_parallel_jobs", skip_serializing_if = "Option::is_none")]
    pub max_parallel_jobs: Option<i32>,
}

impl AgentsRegisterPostRequest {
    pub fn new(agent_id: uuid::Uuid, agent_name: String, agent_version: String, openpgp_public_key: String, openpgp_fingerprint: String, os_name: OsName, os_version: String, arch: Arch, capabilities: Vec<String>) -> AgentsRegisterPostRequest {
        AgentsRegisterPostRequest {
            agent_id,
            agent_name,
            agent_version,
            openpgp_public_key,
            openpgp_fingerprint,
            os_name,
            os_version,
            arch,
            capabilities,
            client_feature_flags_contract_version: None,
            max_parallel_jobs: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OsName {
    #[serde(rename = "linux")]
    Linux,
    #[serde(rename = "macos")]
    Macos,
    #[serde(rename = "windows")]
    Windows,
}

impl Default for OsName {
    fn default() -> OsName {
        Self::Linux
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Arch {
    #[serde(rename = "x86_64")]
    X8664,
    #[serde(rename = "arm64")]
    Arm64,
    #[serde(rename = "armv7")]
    Armv7,
    #[serde(rename = "other")]
    Other,
}

impl Default for Arch {
    fn default() -> Arch {
        Self::X8664
    }
}

