/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsUuidDecisionPostRequest {
    #[serde(rename = "action")]
    pub action: Action,
}

impl AssetsUuidDecisionPostRequest {
    pub fn new(action: Action) -> AssetsUuidDecisionPostRequest {
        AssetsUuidDecisionPostRequest { action }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "KEEP")]
    Keep,
    #[serde(rename = "REJECT")]
    Reject,
    #[serde(rename = "CLEAR")]
    Clear,
}

impl Default for Action {
    fn default() -> Action {
        Self::Keep
    }
}
