/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsUuidDerivedUploadPartPostRequest {
    #[serde(rename = "upload_id")]
    pub upload_id: String,
    #[serde(rename = "part_number")]
    pub part_number: i32,
}

impl AssetsUuidDerivedUploadPartPostRequest {
    pub fn new(upload_id: String, part_number: i32) -> AssetsUuidDerivedUploadPartPostRequest {
        AssetsUuidDerivedUploadPartPostRequest {
            upload_id,
            part_number,
        }
    }
}
