/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsUuidPatchRequest {
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Shared complementary metadata map. Values stay JSON-simple; domains requiring dedicated semantics, storage or security rules must not be hidden implicitly here.
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<std::collections::HashMap<String, models::AssetFieldValue>>,
    #[serde(rename = "captured_at", skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<String>,
    #[serde(rename = "gps_latitude", skip_serializing_if = "Option::is_none")]
    pub gps_latitude: Option<f64>,
    #[serde(rename = "gps_longitude", skip_serializing_if = "Option::is_none")]
    pub gps_longitude: Option<f64>,
    #[serde(rename = "gps_altitude_m", skip_serializing_if = "Option::is_none")]
    pub gps_altitude_m: Option<f64>,
    #[serde(
        rename = "gps_altitude_relative_m",
        skip_serializing_if = "Option::is_none"
    )]
    pub gps_altitude_relative_m: Option<f64>,
    #[serde(
        rename = "gps_altitude_absolute_m",
        skip_serializing_if = "Option::is_none"
    )]
    pub gps_altitude_absolute_m: Option<f64>,
    #[serde(rename = "location_country", skip_serializing_if = "Option::is_none")]
    pub location_country: Option<String>,
    #[serde(rename = "location_city", skip_serializing_if = "Option::is_none")]
    pub location_city: Option<String>,
    #[serde(rename = "location_label", skip_serializing_if = "Option::is_none")]
    pub location_label: Option<String>,
    #[serde(rename = "processing_profile", skip_serializing_if = "Option::is_none")]
    pub processing_profile: Option<ProcessingProfile>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
}

impl AssetsUuidPatchRequest {
    pub fn new() -> AssetsUuidPatchRequest {
        AssetsUuidPatchRequest {
            tags: None,
            notes: None,
            fields: None,
            captured_at: None,
            gps_latitude: None,
            gps_longitude: None,
            gps_altitude_m: None,
            gps_altitude_relative_m: None,
            gps_altitude_absolute_m: None,
            location_country: None,
            location_city: None,
            location_label: None,
            processing_profile: None,
            state: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProcessingProfile {
    #[serde(rename = "video_standard")]
    VideoStandard,
    #[serde(rename = "audio_undefined")]
    AudioUndefined,
    #[serde(rename = "audio_music")]
    AudioMusic,
    #[serde(rename = "audio_voice")]
    AudioVoice,
    #[serde(rename = "photo_standard")]
    PhotoStandard,
}

impl Default for ProcessingProfile {
    fn default() -> ProcessingProfile {
        Self::VideoStandard
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "DECISION_PENDING")]
    DecisionPending,
    #[serde(rename = "DECIDED_KEEP")]
    DecidedKeep,
    #[serde(rename = "DECIDED_REJECT")]
    DecidedReject,
    #[serde(rename = "ARCHIVED")]
    Archived,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl Default for State {
    fn default() -> State {
        Self::DecisionPending
    }
}
