/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsUuidDerivedUploadInitPostRequest {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "size_bytes")]
    pub size_bytes: i32,
    #[serde(rename = "sha256", skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
}

impl AssetsUuidDerivedUploadInitPostRequest {
    pub fn new(
        kind: Kind,
        content_type: String,
        size_bytes: i32,
    ) -> AssetsUuidDerivedUploadInitPostRequest {
        AssetsUuidDerivedUploadInitPostRequest {
            kind,
            content_type,
            size_bytes,
            sha256: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "proxy_video")]
    ProxyVideo,
    #[serde(rename = "proxy_audio")]
    ProxyAudio,
    #[serde(rename = "proxy_photo")]
    ProxyPhoto,
    #[serde(rename = "thumb")]
    Thumb,
    #[serde(rename = "waveform")]
    Waveform,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::ProxyVideo
    }
}
