/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsPurgePostRequest {
    #[serde(rename = "asset_uuids")]
    pub asset_uuids: Vec<uuid::Uuid>,
    #[serde(rename = "confirm")]
    pub confirm: Confirm,
}

impl AssetsPurgePostRequest {
    pub fn new(asset_uuids: Vec<uuid::Uuid>, confirm: Confirm) -> AssetsPurgePostRequest {
        AssetsPurgePostRequest {
            asset_uuids,
            confirm,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Confirm {
    #[serde(rename = "true")]
    True,
}

impl Default for Confirm {
    fn default() -> Confirm {
        Self::True
    }
}

