/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionsApplyPostRequest {
    #[serde(rename = "approval_token")]
    pub approval_token: String,
    #[serde(rename = "confirm")]
    pub confirm: Confirm,
}

impl DecisionsApplyPostRequest {
    pub fn new(approval_token: String, confirm: Confirm) -> DecisionsApplyPostRequest {
        DecisionsApplyPostRequest {
            approval_token,
            confirm,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Confirm {
    #[serde(rename = "true")]
    True,
}

impl Default for Confirm {
    fn default() -> Confirm {
        Self::True
    }
}
