/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsJobIdFailPostRequest {
    #[serde(rename = "lock_token")]
    pub lock_token: String,
    #[serde(rename = "error_code")]
    pub error_code: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "retryable")]
    pub retryable: bool,
}

impl JobsJobIdFailPostRequest {
    pub fn new(
        lock_token: String,
        error_code: String,
        retryable: bool,
    ) -> JobsJobIdFailPostRequest {
        JobsJobIdFailPostRequest {
            lock_token,
            error_code,
            message: None,
            retryable,
        }
    }
}
