/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsLocksGet200Response {
    #[serde(rename = "items")]
    pub items: Vec<models::OpsLocksGet200ResponseItemsInner>,
    /// Total count after filters, before pagination. Items are returned by canonical default order `acquired_at DESC`.
    #[serde(rename = "total")]
    pub total: i32,
}

impl OpsLocksGet200Response {
    pub fn new(
        items: Vec<models::OpsLocksGet200ResponseItemsInner>,
        total: i32,
    ) -> OpsLocksGet200Response {
        OpsLocksGet200Response { items, total }
    }
}
