/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsAgentsGet200Response {
    #[serde(rename = "items")]
    pub items: Vec<models::OpsAgentsGet200ResponseItemsInner>,
    /// Items are returned by canonical default order `last_seen_at DESC`.
    #[serde(rename = "total")]
    pub total: i32,
}

impl OpsAgentsGet200Response {
    pub fn new(items: Vec<models::OpsAgentsGet200ResponseItemsInner>, total: i32) -> OpsAgentsGet200Response {
        OpsAgentsGet200Response {
            items,
            total,
        }
    }
}

