/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsIngestRequeuePostRequest {
    #[serde(rename = "asset_uuid", skip_serializing_if = "Option::is_none")]
    pub asset_uuid: Option<uuid::Uuid>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "include_sidecars", skip_serializing_if = "Option::is_none")]
    pub include_sidecars: Option<bool>,
    #[serde(rename = "include_derived", skip_serializing_if = "Option::is_none")]
    pub include_derived: Option<bool>,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl OpsIngestRequeuePostRequest {
    pub fn new(reason: String) -> OpsIngestRequeuePostRequest {
        OpsIngestRequeuePostRequest {
            asset_uuid: None,
            path: None,
            include_sidecars: None,
            include_derived: None,
            reason,
        }
    }
}

