/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsJobsQueueGet200ResponseByTypeInner {
    #[serde(rename = "job_type")]
    pub job_type: String,
    #[serde(rename = "pending")]
    pub pending: i32,
    #[serde(rename = "claimed")]
    pub claimed: i32,
    #[serde(rename = "failed")]
    pub failed: i32,
    #[serde(rename = "oldest_pending_age_seconds", skip_serializing_if = "Option::is_none")]
    pub oldest_pending_age_seconds: Option<i32>,
}

impl OpsJobsQueueGet200ResponseByTypeInner {
    pub fn new(job_type: String, pending: i32, claimed: i32, failed: i32) -> OpsJobsQueueGet200ResponseByTypeInner {
        OpsJobsQueueGet200ResponseByTypeInner {
            job_type,
            pending,
            claimed,
            failed,
            oldest_pending_age_seconds: None,
        }
    }
}

