/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsReadinessGet200ResponseChecksInner {
    /// Check identifier (e.g. `database`, `ingest_watch_path`, `storage_writable`).
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "message")]
    pub message: String,
}

impl OpsReadinessGet200ResponseChecksInner {
    pub fn new(name: String, status: Status, message: String) -> OpsReadinessGet200ResponseChecksInner {
        OpsReadinessGet200ResponseChecksInner {
            name,
            status,
            message,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "fail")]
    Fail,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}

