/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsLocksGet200ResponseItemsInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "asset_uuid")]
    pub asset_uuid: String,
    #[serde(rename = "lock_type")]
    pub lock_type: String,
    #[serde(rename = "actor_id")]
    pub actor_id: String,
    #[serde(rename = "acquired_at")]
    pub acquired_at: String,
    #[serde(rename = "released_at", skip_serializing_if = "Option::is_none")]
    pub released_at: Option<String>,
}

impl OpsLocksGet200ResponseItemsInner {
    pub fn new(id: String, asset_uuid: String, lock_type: String, actor_id: String, acquired_at: String) -> OpsLocksGet200ResponseItemsInner {
        OpsLocksGet200ResponseItemsInner {
            id,
            asset_uuid,
            lock_type,
            actor_id,
            acquired_at,
            released_at: None,
        }
    }
}

