/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsReadinessGet200Response {
    /// Overall status (`down` when database check fails; `degraded` when critical non-database checks fail but auto-repair is active).
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "self_healing")]
    pub self_healing: Box<models::OpsReadinessGet200ResponseSelfHealing>,
    #[serde(rename = "checks")]
    pub checks: Vec<models::OpsReadinessGet200ResponseChecksInner>,
}

impl OpsReadinessGet200Response {
    pub fn new(status: Status, self_healing: models::OpsReadinessGet200ResponseSelfHealing, checks: Vec<models::OpsReadinessGet200ResponseChecksInner>) -> OpsReadinessGet200Response {
        OpsReadinessGet200Response {
            status,
            self_healing: Box::new(self_healing),
            checks,
        }
    }
}
/// Overall status (`down` when database check fails; `degraded` when critical non-database checks fail but auto-repair is active).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "down")]
    Down,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}

