/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsIngestRequeuePost202ResponseTarget {
    #[serde(rename = "asset_uuid", skip_serializing_if = "Option::is_none")]
    pub asset_uuid: Option<uuid::Uuid>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl OpsIngestRequeuePost202ResponseTarget {
    pub fn new() -> OpsIngestRequeuePost202ResponseTarget {
        OpsIngestRequeuePost202ResponseTarget {
            asset_uuid: None,
            path: None,
        }
    }
}

