/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsIngestRequeuePost202Response {
    #[serde(rename = "accepted")]
    pub accepted: Accepted,
    #[serde(rename = "target")]
    pub target: Box<models::OpsIngestRequeuePost202ResponseTarget>,
    #[serde(rename = "requeued_assets")]
    pub requeued_assets: i32,
    #[serde(rename = "requeued_jobs")]
    pub requeued_jobs: i32,
    #[serde(rename = "deduplicated_jobs")]
    pub deduplicated_jobs: i32,
}

impl OpsIngestRequeuePost202Response {
    pub fn new(accepted: Accepted, target: models::OpsIngestRequeuePost202ResponseTarget, requeued_assets: i32, requeued_jobs: i32, deduplicated_jobs: i32) -> OpsIngestRequeuePost202Response {
        OpsIngestRequeuePost202Response {
            accepted,
            target: Box::new(target),
            requeued_assets,
            requeued_jobs,
            deduplicated_jobs,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Accepted {
    #[serde(rename = "true")]
    True,
}

impl Default for Accepted {
    fn default() -> Accepted {
        Self::True
    }
}

