/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsJobsQueueGet200ResponseSummary {
    #[serde(rename = "pending_total")]
    pub pending_total: i32,
    #[serde(rename = "claimed_total")]
    pub claimed_total: i32,
    #[serde(rename = "failed_total")]
    pub failed_total: i32,
}

impl OpsJobsQueueGet200ResponseSummary {
    pub fn new(
        pending_total: i32,
        claimed_total: i32,
        failed_total: i32,
    ) -> OpsJobsQueueGet200ResponseSummary {
        OpsJobsQueueGet200ResponseSummary {
            pending_total,
            claimed_total,
            failed_total,
        }
    }
}
