/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsAgentsGet200ResponseItemsInnerCurrentJob {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "job_type")]
    pub job_type: String,
    #[serde(rename = "asset_uuid")]
    pub asset_uuid: String,
    #[serde(rename = "claimed_at")]
    pub claimed_at: String,
    #[serde(rename = "locked_until")]
    pub locked_until: String,
}

impl OpsAgentsGet200ResponseItemsInnerCurrentJob {
    pub fn new(job_id: String, job_type: String, asset_uuid: String, claimed_at: String, locked_until: String) -> OpsAgentsGet200ResponseItemsInnerCurrentJob {
        OpsAgentsGet200ResponseItemsInnerCurrentJob {
            job_id,
            job_type,
            asset_uuid,
            claimed_at,
            locked_until,
        }
    }
}

