/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsJobsQueueGet200Response {
    #[serde(rename = "summary")]
    pub summary: Box<models::OpsJobsQueueGet200ResponseSummary>,
    #[serde(rename = "by_type")]
    pub by_type: Vec<models::OpsJobsQueueGet200ResponseByTypeInner>,
}

impl OpsJobsQueueGet200Response {
    pub fn new(summary: models::OpsJobsQueueGet200ResponseSummary, by_type: Vec<models::OpsJobsQueueGet200ResponseByTypeInner>) -> OpsJobsQueueGet200Response {
        OpsJobsQueueGet200Response {
            summary: Box::new(summary),
            by_type,
        }
    }
}

