/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsAgentsGet200ResponseItemsInner {
    #[serde(rename = "agent_id")]
    pub agent_id: uuid::Uuid,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "agent_name")]
    pub agent_name: String,
    #[serde(rename = "agent_version")]
    pub agent_version: String,
    #[serde(rename = "os_name", skip_serializing_if = "Option::is_none")]
    pub os_name: Option<OsName>,
    #[serde(rename = "os_version", skip_serializing_if = "Option::is_none")]
    pub os_version: Option<String>,
    #[serde(rename = "arch", skip_serializing_if = "Option::is_none")]
    pub arch: Option<String>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "identity_conflict")]
    pub identity_conflict: bool,
    #[serde(rename = "last_seen_at")]
    pub last_seen_at: String,
    #[serde(rename = "last_register_at")]
    pub last_register_at: String,
    #[serde(rename = "last_heartbeat_at", skip_serializing_if = "Option::is_none")]
    pub last_heartbeat_at: Option<String>,
    #[serde(rename = "effective_capabilities")]
    pub effective_capabilities: Vec<String>,
    #[serde(rename = "capability_warnings")]
    pub capability_warnings: Vec<String>,
    #[serde(rename = "current_job", skip_serializing_if = "Option::is_none")]
    pub current_job: Option<Box<models::OpsAgentsGet200ResponseItemsInnerCurrentJob>>,
    #[serde(rename = "last_successful_job", skip_serializing_if = "Option::is_none")]
    pub last_successful_job: Option<Box<models::OpsAgentsGet200ResponseItemsInnerLastSuccessfulJob>>,
    #[serde(rename = "last_failed_job", skip_serializing_if = "Option::is_none")]
    pub last_failed_job: Option<Box<models::OpsAgentsGet200ResponseItemsInnerLastFailedJob>>,
    #[serde(rename = "debug")]
    pub debug: Box<models::OpsAgentsGet200ResponseItemsInnerDebug>,
}

impl OpsAgentsGet200ResponseItemsInner {
    pub fn new(agent_id: uuid::Uuid, client_id: String, agent_name: String, agent_version: String, status: Status, identity_conflict: bool, last_seen_at: String, last_register_at: String, effective_capabilities: Vec<String>, capability_warnings: Vec<String>, debug: models::OpsAgentsGet200ResponseItemsInnerDebug) -> OpsAgentsGet200ResponseItemsInner {
        OpsAgentsGet200ResponseItemsInner {
            agent_id,
            client_id,
            agent_name,
            agent_version,
            os_name: None,
            os_version: None,
            arch: None,
            status,
            identity_conflict,
            last_seen_at,
            last_register_at,
            last_heartbeat_at: None,
            effective_capabilities,
            capability_warnings,
            current_job: None,
            last_successful_job: None,
            last_failed_job: None,
            debug: Box::new(debug),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OsName {
    #[serde(rename = "linux")]
    Linux,
    #[serde(rename = "macos")]
    Macos,
    #[serde(rename = "windows")]
    Windows,
}

impl Default for OsName {
    fn default() -> OsName {
        Self::Linux
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "online_idle")]
    OnlineIdle,
    #[serde(rename = "online_busy")]
    OnlineBusy,
    #[serde(rename = "stale")]
    Stale,
}

impl Default for Status {
    fn default() -> Status {
        Self::OnlineIdle
    }
}

