/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsAgentsGet200ResponseItemsInnerDebug {
    #[serde(rename = "max_parallel_jobs")]
    pub max_parallel_jobs: i32,
    #[serde(rename = "feature_flags_contract_version", skip_serializing_if = "Option::is_none")]
    pub feature_flags_contract_version: Option<String>,
    #[serde(rename = "effective_feature_flags_contract_version", skip_serializing_if = "Option::is_none")]
    pub effective_feature_flags_contract_version: Option<String>,
    #[serde(rename = "server_time_skew_seconds", skip_serializing_if = "Option::is_none")]
    pub server_time_skew_seconds: Option<i32>,
}

impl OpsAgentsGet200ResponseItemsInnerDebug {
    pub fn new(max_parallel_jobs: i32) -> OpsAgentsGet200ResponseItemsInnerDebug {
        OpsAgentsGet200ResponseItemsInnerDebug {
            max_parallel_jobs,
            feature_flags_contract_version: None,
            effective_feature_flags_contract_version: None,
            server_time_skew_seconds: None,
        }
    }
}

