/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsIngestUnmatchedGet200ResponseItemsInner {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "reason")]
    pub reason: Reason,
    #[serde(rename = "detected_at")]
    pub detected_at: String,
}

impl OpsIngestUnmatchedGet200ResponseItemsInner {
    pub fn new(path: String, reason: Reason, detected_at: String) -> OpsIngestUnmatchedGet200ResponseItemsInner {
        OpsIngestUnmatchedGet200ResponseItemsInner {
            path,
            reason,
            detected_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "missing_parent")]
    MissingParent,
    #[serde(rename = "ambiguous_parent")]
    AmbiguousParent,
    #[serde(rename = "disabled_by_policy")]
    DisabledByPolicy,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::MissingParent
    }
}

