/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsIngestDiagnosticsGet200Response {
    #[serde(rename = "queued")]
    pub queued: i32,
    #[serde(rename = "missing")]
    pub missing: i32,
    #[serde(rename = "unmatched_sidecars")]
    pub unmatched_sidecars: i32,
    #[serde(rename = "latest_unmatched")]
    pub latest_unmatched: Vec<models::OpsIngestDiagnosticsGet200ResponseLatestUnmatchedInner>,
}

impl OpsIngestDiagnosticsGet200Response {
    pub fn new(queued: i32, missing: i32, unmatched_sidecars: i32, latest_unmatched: Vec<models::OpsIngestDiagnosticsGet200ResponseLatestUnmatchedInner>) -> OpsIngestDiagnosticsGet200Response {
        OpsIngestDiagnosticsGet200Response {
            queued,
            missing,
            unmatched_sidecars,
            latest_unmatched,
        }
    }
}

