/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpsReadinessGet200ResponseSelfHealing {
    #[serde(rename = "active")]
    pub active: bool,
    /// Auto-repair deadline in UTC; null when `active=false`.
    #[serde(rename = "deadline_at")]
    pub deadline_at: String,
    /// Normative maximum auto-repair window in seconds.
    #[serde(rename = "max_self_healing_seconds")]
    pub max_self_healing_seconds: MaxSelfHealingSeconds,
}

impl OpsReadinessGet200ResponseSelfHealing {
    pub fn new(
        active: bool,
        deadline_at: String,
        max_self_healing_seconds: MaxSelfHealingSeconds,
    ) -> OpsReadinessGet200ResponseSelfHealing {
        OpsReadinessGet200ResponseSelfHealing {
            active,
            deadline_at,
            max_self_healing_seconds,
        }
    }
}
/// Normative maximum auto-repair window in seconds.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaxSelfHealingSeconds {
    #[serde(rename = "300")]
    Variant300,
}

impl Default for MaxSelfHealingSeconds {
    fn default() -> MaxSelfHealingSeconds {
        Self::Variant300
    }
}
