/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppFeaturesResponse {
    /// Application-level feature switches. Effective feature availability requires Core `FeatureFlags` AND `AppFeatureEnabled`. `features.ai` controls MCP global availability (false => MCP disabled).
    #[serde(rename = "app_feature_enabled")]
    pub app_feature_enabled: std::collections::HashMap<String, bool>,
    /// Canonical list of non-disableable v1 global core feature keys.
    #[serde(rename = "core_v1_global_features")]
    pub core_v1_global_features: Vec<models::CoreV1GlobalFeatureKey>,
    #[serde(rename = "feature_governance")]
    pub feature_governance: Vec<models::FeatureGovernanceRule>,
}

impl AppFeaturesResponse {
    pub fn new(
        app_feature_enabled: std::collections::HashMap<String, bool>,
        core_v1_global_features: Vec<models::CoreV1GlobalFeatureKey>,
        feature_governance: Vec<models::FeatureGovernanceRule>,
    ) -> AppFeaturesResponse {
        AppFeaturesResponse {
            app_feature_enabled,
            core_v1_global_features,
            feature_governance,
        }
    }
}
