/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppFeaturesResponse {
    /// Application-level feature switches. Effective feature availability requires Core `FeatureFlags` AND `AppFeatureEnabled`. `features.ai` gates pre-release dépendantes de l'AI capabilities ahead of their validated v1.1+ rollout. 
    #[serde(rename = "app_feature_enabled")]
    pub app_feature_enabled: std::collections::HashMap<String, bool>,
    #[serde(rename = "app_feature_explanations")]
    pub app_feature_explanations: std::collections::HashMap<String, models::FeatureExplanation>,
    /// Canonical list of non-disableable v1 global core feature keys.
    #[serde(rename = "core_v1_global_features")]
    pub core_v1_global_features: Vec<models::CoreV1GlobalFeatureKey>,
    #[serde(rename = "feature_governance")]
    pub feature_governance: Vec<models::FeatureGovernanceRule>,
}

impl AppFeaturesResponse {
    pub fn new(app_feature_enabled: std::collections::HashMap<String, bool>, app_feature_explanations: std::collections::HashMap<String, models::FeatureExplanation>, core_v1_global_features: Vec<models::CoreV1GlobalFeatureKey>, feature_governance: Vec<models::FeatureGovernanceRule>) -> AppFeaturesResponse {
        AppFeaturesResponse {
            app_feature_enabled,
            app_feature_explanations,
            core_v1_global_features,
            feature_governance,
        }
    }
}

