/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppFeaturesUpdateRequest {
    /// Application-level feature switches. Effective feature availability requires Core `FeatureFlags` AND `AppFeatureEnabled`. `features.ai` controls MCP global availability (false => MCP disabled).
    #[serde(rename = "app_feature_enabled")]
    pub app_feature_enabled: std::collections::HashMap<String, bool>,
}

impl AppFeaturesUpdateRequest {
    pub fn new(
        app_feature_enabled: std::collections::HashMap<String, bool>,
    ) -> AppFeaturesUpdateRequest {
        AppFeaturesUpdateRequest {
            app_feature_enabled,
        }
    }
}
