/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetSummary {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "media_type")]
    pub media_type: MediaType,
    #[serde(rename = "state")]
    pub state: models::AssetState,
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of the last accepted business mutation on this asset. Informational only; not a write precondition.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Strong opaque asset revision tag to be reused in `If-Match` for the next mutation. Changes on any accepted human-visible business mutation and stays stable for purely technical noise with no review/operator impact.
    #[serde(rename = "revision_etag")]
    pub revision_etag: String,
    #[serde(rename = "captured_at", skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "has_proxy", skip_serializing_if = "Option::is_none")]
    pub has_proxy: Option<bool>,
    #[serde(rename = "thumb_url", skip_serializing_if = "Option::is_none")]
    pub thumb_url: Option<String>,
}

impl AssetSummary {
    pub fn new(uuid: String, media_type: MediaType, state: models::AssetState, created_at: String, updated_at: String, revision_etag: String) -> AssetSummary {
        AssetSummary {
            uuid,
            name: None,
            media_type,
            state,
            created_at,
            updated_at,
            revision_etag,
            captured_at: None,
            duration: None,
            tags: None,
            has_proxy: None,
            thumb_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "VIDEO")]
    Video,
    #[serde(rename = "PHOTO")]
    Photo,
    #[serde(rename = "AUDIO")]
    Audio,
}

impl Default for MediaType {
    fn default() -> MediaType {
        Self::Video
    }
}

