/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetPaths {
    /// Stable logical storage identifier emitted by Core and mapped locally by agents.
    #[serde(rename = "storage_id")]
    pub storage_id: String,
    /// Relative storage path only. Must never be absolute, contain parent traversal (`..`), or contain null bytes. 
    #[serde(rename = "original_relative")]
    pub original_relative: String,
    #[serde(rename = "sidecars_relative", skip_serializing_if = "Option::is_none")]
    pub sidecars_relative: Option<Vec<String>>,
}

impl AssetPaths {
    pub fn new(storage_id: String, original_relative: String) -> AssetPaths {
        AssetPaths {
            storage_id,
            original_relative,
            sidecars_relative: None,
        }
    }
}

