/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDetail {
    #[serde(rename = "summary")]
    pub summary: Box<models::AssetSummary>,
    #[serde(rename = "paths", skip_serializing_if = "Option::is_none")]
    pub paths: Option<Box<models::AssetPaths>>,
    #[serde(rename = "processing", skip_serializing_if = "Option::is_none")]
    pub processing: Option<Box<models::AssetProcessing>>,
    #[serde(rename = "derived", skip_serializing_if = "Option::is_none")]
    pub derived: Option<Box<models::AssetDerived>>,
    #[serde(rename = "transcript", skip_serializing_if = "Option::is_none")]
    pub transcript: Option<Box<models::AssetTranscript>>,
    #[serde(rename = "decisions", skip_serializing_if = "Option::is_none")]
    pub decisions: Option<Box<models::AssetDecisions>>,
    #[serde(rename = "audit", skip_serializing_if = "Option::is_none")]
    pub audit: Option<Box<models::AssetAudit>>,
}

impl AssetDetail {
    pub fn new(summary: models::AssetSummary) -> AssetDetail {
        AssetDetail {
            summary: Box::new(summary),
            paths: None,
            processing: None,
            derived: None,
            transcript: None,
            decisions: None,
            audit: None,
        }
    }
}
