/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDecisions {
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<Current>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::AssetDecisionsHistoryInner>>,
}

impl AssetDecisions {
    pub fn new() -> AssetDecisions {
        AssetDecisions {
            current: None,
            history: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Current {
    #[serde(rename = "KEEP")]
    Keep,
    #[serde(rename = "REJECT")]
    Reject,
}

impl Default for Current {
    fn default() -> Current {
        Self::Keep
    }
}
