/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetState {
    #[serde(rename = "DISCOVERED")]
    Discovered,
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "PROCESSING_REVIEW")]
    ProcessingReview,
    #[serde(rename = "PROCESSED")]
    Processed,
    #[serde(rename = "DECISION_PENDING")]
    DecisionPending,
    #[serde(rename = "DECIDED_KEEP")]
    DecidedKeep,
    #[serde(rename = "DECIDED_REJECT")]
    DecidedReject,
    #[serde(rename = "MOVE_QUEUED")]
    MoveQueued,
    #[serde(rename = "ARCHIVED")]
    Archived,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "PURGED")]
    Purged,
}

impl std::fmt::Display for AssetState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Discovered => write!(f, "DISCOVERED"),
            Self::Ready => write!(f, "READY"),
            Self::ProcessingReview => write!(f, "PROCESSING_REVIEW"),
            Self::Processed => write!(f, "PROCESSED"),
            Self::DecisionPending => write!(f, "DECISION_PENDING"),
            Self::DecidedKeep => write!(f, "DECIDED_KEEP"),
            Self::DecidedReject => write!(f, "DECIDED_REJECT"),
            Self::MoveQueued => write!(f, "MOVE_QUEUED"),
            Self::Archived => write!(f, "ARCHIVED"),
            Self::Rejected => write!(f, "REJECTED"),
            Self::Purged => write!(f, "PURGED"),
        }
    }
}

impl Default for AssetState {
    fn default() -> AssetState {
        Self::Discovered
    }
}
