/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetAuditRevisionHistoryInner {
    #[serde(rename = "revision")]
    pub revision: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "is_current")]
    pub is_current: bool,
    #[serde(rename = "published_at", skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,
    #[serde(rename = "validation_status")]
    pub validation_status: ValidationStatus,
}

impl AssetAuditRevisionHistoryInner {
    pub fn new(
        revision: i32,
        created_at: String,
        is_current: bool,
        validation_status: ValidationStatus,
    ) -> AssetAuditRevisionHistoryInner {
        AssetAuditRevisionHistoryInner {
            revision,
            created_at,
            is_current,
            published_at: None,
            validation_status,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ValidationStatus {
    #[serde(rename = "VALIDATED")]
    Validated,
    #[serde(rename = "PENDING_VALIDATION")]
    PendingValidation,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl Default for ValidationStatus {
    fn default() -> ValidationStatus {
        Self::Validated
    }
}
