/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDerived {
    #[serde(rename = "proxy_video_url", skip_serializing_if = "Option::is_none")]
    pub proxy_video_url: Option<String>,
    #[serde(rename = "proxy_audio_url", skip_serializing_if = "Option::is_none")]
    pub proxy_audio_url: Option<String>,
    #[serde(rename = "proxy_photo_url", skip_serializing_if = "Option::is_none")]
    pub proxy_photo_url: Option<String>,
    /// Optional server-generated waveform file URL. If absent, UI clients must render a simple local waveform from audio (pure JS). 
    #[serde(rename = "waveform_url", skip_serializing_if = "Option::is_none")]
    pub waveform_url: Option<String>,
    #[serde(rename = "thumbs", skip_serializing_if = "Option::is_none")]
    pub thumbs: Option<Vec<String>>,
}

impl AssetDerived {
    pub fn new() -> AssetDerived {
        AssetDerived {
            proxy_video_url: None,
            proxy_audio_url: None,
            proxy_photo_url: None,
            waveform_url: None,
            thumbs: None,
        }
    }
}

