/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetSummary {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "media_type")]
    pub media_type: MediaType,
    #[serde(rename = "state")]
    pub state: models::AssetState,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "captured_at", skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "has_proxy", skip_serializing_if = "Option::is_none")]
    pub has_proxy: Option<bool>,
    #[serde(rename = "thumb_url", skip_serializing_if = "Option::is_none")]
    pub thumb_url: Option<String>,
}

impl AssetSummary {
    pub fn new(
        uuid: String,
        media_type: MediaType,
        state: models::AssetState,
        created_at: String,
    ) -> AssetSummary {
        AssetSummary {
            uuid,
            media_type,
            state,
            created_at,
            captured_at: None,
            duration: None,
            tags: None,
            has_proxy: None,
            thumb_url: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "VIDEO")]
    Video,
    #[serde(rename = "PHOTO")]
    Photo,
    #[serde(rename = "AUDIO")]
    Audio,
}

impl Default for MediaType {
    fn default() -> MediaType {
        Self::Video
    }
}
