/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetProcessing {
    #[serde(rename = "facts_done", skip_serializing_if = "Option::is_none")]
    pub facts_done: Option<bool>,
    #[serde(rename = "thumbs_done", skip_serializing_if = "Option::is_none")]
    pub thumbs_done: Option<bool>,
    #[serde(rename = "proxy_done", skip_serializing_if = "Option::is_none")]
    pub proxy_done: Option<bool>,
    #[serde(rename = "waveform_done", skip_serializing_if = "Option::is_none")]
    pub waveform_done: Option<bool>,
    #[serde(rename = "processing_profile", skip_serializing_if = "Option::is_none")]
    pub processing_profile: Option<String>,
    #[serde(
        rename = "review_processing_version",
        skip_serializing_if = "Option::is_none"
    )]
    pub review_processing_version: Option<String>,
}

impl AssetProcessing {
    pub fn new() -> AssetProcessing {
        AssetProcessing {
            facts_done: None,
            thumbs_done: None,
            proxy_done: None,
            waveform_done: None,
            processing_profile: None,
            review_processing_version: None,
        }
    }
}
