/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetAudit {
    /// Chronological path history in ascending order, using canonical relative paths only.
    #[serde(rename = "path_history", skip_serializing_if = "Option::is_none")]
    pub path_history: Option<Vec<String>>,
    /// Append-only revision timeline in ascending `revision` order. The entry marked `is_current=true` matches the current `summary.revision_etag`.
    #[serde(rename = "revision_history", skip_serializing_if = "Option::is_none")]
    pub revision_history: Option<Vec<models::AssetAuditRevisionHistoryInner>>,
}

impl AssetAudit {
    pub fn new() -> AssetAudit {
        AssetAudit {
            path_history: None,
            revision_history: None,
        }
    }
}

