/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetTranscript {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "text_preview", skip_serializing_if = "Option::is_none")]
    pub text_preview: Option<String>,
    /// Timestamp of the last accepted business mutation on this asset. Informational only; not a write precondition.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Strong opaque asset revision tag to be reused in `If-Match` for the next mutation.
    #[serde(rename = "revision_etag", skip_serializing_if = "Option::is_none")]
    pub revision_etag: Option<String>,
}

impl AssetTranscript {
    pub fn new() -> AssetTranscript {
        AssetTranscript {
            status: None,
            text_preview: None,
            updated_at: None,
            revision_etag: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "DONE")]
    Done,
    #[serde(rename = "FAILED")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::None
    }
}

