/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDerived {
    /// Stable Core URL for the current video preview. Served directly by Core in v1.
    #[serde(rename = "preview_video_url", skip_serializing_if = "Option::is_none")]
    pub preview_video_url: Option<String>,
    /// Stable Core URL for the current audio preview. Served directly by Core in v1.
    #[serde(rename = "preview_audio_url", skip_serializing_if = "Option::is_none")]
    pub preview_audio_url: Option<String>,
    /// Stable Core URL for the current photo preview. Served directly by Core in v1.
    #[serde(rename = "preview_photo_url", skip_serializing_if = "Option::is_none")]
    pub preview_photo_url: Option<String>,
    /// Stable Core URL for the current waveform payload. Required when the effective processing profile requires waveform data beyond READY.
    #[serde(rename = "waveform_url", skip_serializing_if = "Option::is_none")]
    pub waveform_url: Option<String>,
    /// Video-only thumbnails.
    #[serde(rename = "thumbs", skip_serializing_if = "Option::is_none")]
    pub thumbs: Option<Vec<String>>,
}

impl AssetDerived {
    pub fn new() -> AssetDerived {
        AssetDerived {
            preview_video_url: None,
            preview_audio_url: None,
            preview_photo_url: None,
            waveform_url: None,
            thumbs: None,
        }
    }
}
