/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDetail {
    #[serde(rename = "summary")]
    pub summary: Box<models::AssetSummary>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Shared complementary metadata map. Values stay JSON-simple; domains requiring dedicated semantics, storage or security rules must not be hidden implicitly here.
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<std::collections::HashMap<String, models::AssetFieldValue>>,
    #[serde(rename = "paths")]
    pub paths: Box<models::AssetPaths>,
    #[serde(rename = "processing")]
    pub processing: Box<models::AssetProcessing>,
    #[serde(rename = "derived")]
    pub derived: Box<models::AssetDerived>,
    /// Pre-release field only. Outside v1 conformance scope; may be exposed earlier under feature flags before validated v1.1+ rollout.
    #[serde(rename = "transcript", skip_serializing_if = "Option::is_none")]
    pub transcript: Option<Box<models::AssetTranscript>>,
    #[serde(rename = "decisions")]
    pub decisions: Box<models::AssetDecisions>,
    #[serde(rename = "audit")]
    pub audit: Box<models::AssetAudit>,
}

impl AssetDetail {
    pub fn new(
        summary: models::AssetSummary,
        paths: models::AssetPaths,
        processing: models::AssetProcessing,
        derived: models::AssetDerived,
        decisions: models::AssetDecisions,
        audit: models::AssetAudit,
    ) -> AssetDetail {
        AssetDetail {
            summary: Box::new(summary),
            notes: None,
            fields: None,
            paths: Box::new(paths),
            processing: Box::new(processing),
            derived: Box::new(derived),
            transcript: None,
            decisions: Box::new(decisions),
            audit: Box::new(audit),
        }
    }
}
