/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthDevicePollResponse {
    AuthDevicePollPending(Box<models::AuthDevicePollPending>),
    AuthDevicePollApproved(Box<models::AuthDevicePollApproved>),
    AuthDevicePollDenied(Box<models::AuthDevicePollDenied>),
    AuthDevicePollExpired(Box<models::AuthDevicePollExpired>),
}

impl Default for AuthDevicePollResponse {
    fn default() -> Self {
        Self::AuthDevicePollPending(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl Default for Status {
    fn default() -> Status {
        Self::Expired
    }
}
