/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLoginRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
    /// Optional client identifier. If omitted, server derives one from runtime client identity.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "client_kind", skip_serializing_if = "Option::is_none")]
    pub client_kind: Option<models::ClientKind>,
    /// 6-digit TOTP code when 2FA is enabled on account.
    #[serde(rename = "otp_code", skip_serializing_if = "Option::is_none")]
    pub otp_code: Option<String>,
    /// One-shot backup code when TOTP app is unavailable.
    #[serde(rename = "recovery_code", skip_serializing_if = "Option::is_none")]
    pub recovery_code: Option<String>,
}

impl AuthLoginRequest {
    pub fn new(email: String, password: String) -> AuthLoginRequest {
        AuthLoginRequest {
            email,
            password,
            client_id: None,
            client_kind: None,
            otp_code: None,
            recovery_code: None,
        }
    }
}
