/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthDeviceStartRequest {
    #[serde(rename = "client_kind")]
    pub client_kind: models::NonUiClientKind,
    #[serde(rename = "client_label", skip_serializing_if = "Option::is_none")]
    pub client_label: Option<String>,
}

impl AuthDeviceStartRequest {
    pub fn new(client_kind: models::NonUiClientKind) -> AuthDeviceStartRequest {
        AuthDeviceStartRequest {
            client_kind,
            client_label: None,
        }
    }
}
