/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthDevicePollApproved {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "client_kind")]
    pub client_kind: models::NonUiClientKind,
    /// One-shot credential shown only once after approval.
    #[serde(rename = "secret_key")]
    pub secret_key: String,
    /// Timestamp of the human approval performed in UI_WEB.
    #[serde(rename = "approved_at")]
    pub approved_at: String,
    /// Audit identifier of the human approver in UI_WEB.
    #[serde(rename = "approved_by_user_id")]
    pub approved_by_user_id: uuid::Uuid,
}

impl AuthDevicePollApproved {
    pub fn new(
        status: Status,
        client_id: String,
        client_kind: models::NonUiClientKind,
        secret_key: String,
        approved_at: String,
        approved_by_user_id: uuid::Uuid,
    ) -> AuthDevicePollApproved {
        AuthDevicePollApproved {
            status,
            client_id,
            client_kind,
            secret_key,
            approved_at,
            approved_by_user_id,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "APPROVED")]
    Approved,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
