/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthClientTokenSuccess {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "client_kind")]
    pub client_kind: models::NonUiClientKind,
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "token_type")]
    pub token_type: TokenType,
    /// Access token lifetime in seconds.
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i32>,
}

impl AuthClientTokenSuccess {
    pub fn new(
        client_id: String,
        client_kind: models::NonUiClientKind,
        access_token: String,
        token_type: TokenType,
    ) -> AuthClientTokenSuccess {
        AuthClientTokenSuccess {
            client_id,
            client_kind,
            access_token,
            token_type,
            expires_in: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenType {
    #[serde(rename = "Bearer")]
    Bearer,
}

impl Default for TokenType {
    fn default() -> TokenType {
        Self::Bearer
    }
}
