/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Auth2faSetupResponse {
    #[serde(rename = "method")]
    pub method: Method,
    #[serde(rename = "issuer")]
    pub issuer: String,
    /// Login identifier shown in authenticator app.
    #[serde(rename = "account_name")]
    pub account_name: String,
    /// Base32 TOTP secret (show once during setup).
    #[serde(rename = "secret")]
    pub secret: String,
    /// Provisioning URI for authenticator apps.
    #[serde(rename = "otpauth_uri")]
    pub otpauth_uri: String,
    /// Optional inline SVG QR code payload.
    #[serde(rename = "qr_svg", skip_serializing_if = "Option::is_none")]
    pub qr_svg: Option<String>,
}

impl Auth2faSetupResponse {
    pub fn new(
        method: Method,
        issuer: String,
        account_name: String,
        secret: String,
        otpauth_uri: String,
    ) -> Auth2faSetupResponse {
        Auth2faSetupResponse {
            method,
            issuer,
            account_name,
            secret,
            otpauth_uri,
            qr_svg: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "TOTP")]
    Totp,
}

impl Default for Method {
    fn default() -> Method {
        Self::Totp
    }
}
