/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSession {
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "last_used_at")]
    pub last_used_at: String,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "is_current")]
    pub is_current: bool,
    #[serde(rename = "device_label", skip_serializing_if = "Option::is_none")]
    pub device_label: Option<String>,
    #[serde(rename = "browser", skip_serializing_if = "Option::is_none")]
    pub browser: Option<String>,
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<String>,
    #[serde(
        rename = "ip_address_last_seen",
        skip_serializing_if = "Option::is_none"
    )]
    pub ip_address_last_seen: Option<String>,
}

impl AuthSession {
    pub fn new(
        session_id: String,
        client_id: String,
        created_at: String,
        last_used_at: String,
        is_current: bool,
    ) -> AuthSession {
        AuthSession {
            session_id,
            client_id,
            created_at,
            last_used_at,
            expires_at: None,
            is_current,
            device_label: None,
            browser: None,
            os: None,
            ip_address_last_seen: None,
        }
    }
}
