/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRotateClientSecretResponse {
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// Returned once at rotation time.
    #[serde(rename = "secret_key")]
    pub secret_key: String,
    #[serde(rename = "rotated_at", skip_serializing_if = "Option::is_none")]
    pub rotated_at: Option<String>,
}

impl AuthRotateClientSecretResponse {
    pub fn new(client_id: String, secret_key: String) -> AuthRotateClientSecretResponse {
        AuthRotateClientSecretResponse {
            client_id,
            secret_key,
            rotated_at: None,
        }
    }
}
