/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMcpRegisterRequest {
    #[serde(rename = "client_label", skip_serializing_if = "Option::is_none")]
    pub client_label: Option<String>,
    #[serde(rename = "openpgp_public_key")]
    pub openpgp_public_key: String,
    #[serde(rename = "openpgp_fingerprint")]
    pub openpgp_fingerprint: String,
}

impl AuthMcpRegisterRequest {
    pub fn new(openpgp_public_key: String, openpgp_fingerprint: String) -> AuthMcpRegisterRequest {
        AuthMcpRegisterRequest {
            client_label: None,
            openpgp_public_key,
            openpgp_fingerprint,
        }
    }
}

