/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMcpRegisterResponse {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "client_kind")]
    pub client_kind: ClientKind,
    #[serde(rename = "openpgp_fingerprint")]
    pub openpgp_fingerprint: String,
    #[serde(rename = "registered_at", skip_serializing_if = "Option::is_none")]
    pub registered_at: Option<String>,
    #[serde(rename = "rotated_at", skip_serializing_if = "Option::is_none")]
    pub rotated_at: Option<String>,
}

impl AuthMcpRegisterResponse {
    pub fn new(client_id: String, client_kind: ClientKind, openpgp_fingerprint: String) -> AuthMcpRegisterResponse {
        AuthMcpRegisterResponse {
            client_id,
            client_kind,
            openpgp_fingerprint,
            registered_at: None,
            rotated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientKind {
    #[serde(rename = "MCP")]
    Mcp,
}

impl Default for ClientKind {
    fn default() -> ClientKind {
        Self::Mcp
    }
}

