/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientKind : Form factor identifier for interactive login flows.
/// Form factor identifier for interactive login flows.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientKind {
    #[serde(rename = "UI_WEB")]
    UiWeb,
    #[serde(rename = "UI_MOBILE")]
    UiMobile,
    #[serde(rename = "AGENT")]
    Agent,
}

impl std::fmt::Display for ClientKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UiWeb => write!(f, "UI_WEB"),
            Self::UiMobile => write!(f, "UI_MOBILE"),
            Self::Agent => write!(f, "AGENT"),
        }
    }
}

impl Default for ClientKind {
    fn default() -> ClientKind {
        Self::UiWeb
    }
}
