/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CoreV1GlobalFeatureKey {
    #[serde(rename = "features.core.auth")]
    FeaturesCoreAuth,
    #[serde(rename = "features.core.assets.lifecycle")]
    FeaturesCoreAssetsLifecycle,
    #[serde(rename = "features.core.jobs.runtime")]
    FeaturesCoreJobsRuntime,
    #[serde(rename = "features.core.search.query")]
    FeaturesCoreSearchQuery,
    #[serde(rename = "features.core.policy.runtime")]
    FeaturesCorePolicyRuntime,
    #[serde(rename = "features.core.derived.access")]
    FeaturesCoreDerivedAccess,
    #[serde(rename = "features.core.clients.bootstrap")]
    FeaturesCoreClientsBootstrap,
}

impl std::fmt::Display for CoreV1GlobalFeatureKey {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FeaturesCoreAuth => write!(f, "features.core.auth"),
            Self::FeaturesCoreAssetsLifecycle => write!(f, "features.core.assets.lifecycle"),
            Self::FeaturesCoreJobsRuntime => write!(f, "features.core.jobs.runtime"),
            Self::FeaturesCoreSearchQuery => write!(f, "features.core.search.query"),
            Self::FeaturesCorePolicyRuntime => write!(f, "features.core.policy.runtime"),
            Self::FeaturesCoreDerivedAccess => write!(f, "features.core.derived.access"),
            Self::FeaturesCoreClientsBootstrap => write!(f, "features.core.clients.bootstrap"),
        }
    }
}

impl Default for CoreV1GlobalFeatureKey {
    fn default() -> CoreV1GlobalFeatureKey {
        Self::FeaturesCoreAuth
    }
}
