/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DerivedPatchDerivedManifestInner {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "ref")]
    pub r#ref: String,
    #[serde(rename = "size_bytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i32>,
    #[serde(rename = "sha256", skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
}

impl DerivedPatchDerivedManifestInner {
    pub fn new(kind: Kind, r#ref: String) -> DerivedPatchDerivedManifestInner {
        DerivedPatchDerivedManifestInner {
            kind,
            r#ref,
            size_bytes: None,
            sha256: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "preview_video")]
    PreviewVideo,
    #[serde(rename = "preview_audio")]
    PreviewAudio,
    #[serde(rename = "preview_photo")]
    PreviewPhoto,
    #[serde(rename = "thumb")]
    Thumb,
    #[serde(rename = "waveform")]
    Waveform,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::PreviewVideo
    }
}

