/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "retryable")]
    pub retryable: bool,
    #[serde(rename = "correlation_id")]
    pub correlation_id: String,
}

impl ErrorResponse {
    pub fn new(
        code: Code,
        message: String,
        retryable: bool,
        correlation_id: String,
    ) -> ErrorResponse {
        ErrorResponse {
            code,
            message,
            details: None,
            retryable,
            correlation_id,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized,
    #[serde(rename = "EMAIL_NOT_VERIFIED")]
    EmailNotVerified,
    #[serde(rename = "FORBIDDEN_SCOPE")]
    ForbiddenScope,
    #[serde(rename = "FORBIDDEN_ACTOR")]
    ForbiddenActor,
    #[serde(rename = "USER_NOT_FOUND")]
    UserNotFound,
    #[serde(rename = "STATE_CONFLICT")]
    StateConflict,
    #[serde(rename = "IDEMPOTENCY_CONFLICT")]
    IdempotencyConflict,
    #[serde(rename = "STALE_LOCK_TOKEN")]
    StaleLockToken,
    #[serde(rename = "NAME_COLLISION_EXHAUSTED")]
    NameCollisionExhausted,
    #[serde(rename = "PURGED")]
    Purged,
    #[serde(rename = "VALIDATION_FAILED")]
    ValidationFailed,
    #[serde(rename = "INVALID_TOKEN")]
    InvalidToken,
    #[serde(rename = "LOCK_REQUIRED")]
    LockRequired,
    #[serde(rename = "LOCK_INVALID")]
    LockInvalid,
    #[serde(rename = "TOO_MANY_ATTEMPTS")]
    TooManyAttempts,
    #[serde(rename = "MFA_REQUIRED")]
    MfaRequired,
    #[serde(rename = "INVALID_2FA_CODE")]
    Invalid2FaCode,
    #[serde(rename = "MFA_ALREADY_ENABLED")]
    MfaAlreadyEnabled,
    #[serde(rename = "MFA_NOT_ENABLED")]
    MfaNotEnabled,
    #[serde(rename = "INVALID_DEVICE_CODE")]
    InvalidDeviceCode,
    #[serde(rename = "EXPIRED_DEVICE_CODE")]
    ExpiredDeviceCode,
    #[serde(rename = "UNSUPPORTED_FEATURE_FLAGS_CONTRACT_VERSION")]
    UnsupportedFeatureFlagsContractVersion,
    #[serde(rename = "SLOW_DOWN")]
    SlowDown,
    #[serde(rename = "RATE_LIMITED")]
    RateLimited,
    #[serde(rename = "TEMPORARY_UNAVAILABLE")]
    TemporaryUnavailable,
}

impl Default for Code {
    fn default() -> Code {
        Self::Unauthorized
    }
}
