/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FactsPatch {
    #[serde(rename = "duration_ms", skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[serde(rename = "media_format", skip_serializing_if = "Option::is_none")]
    pub media_format: Option<String>,
    #[serde(rename = "video_codec", skip_serializing_if = "Option::is_none")]
    pub video_codec: Option<String>,
    #[serde(rename = "audio_codec", skip_serializing_if = "Option::is_none")]
    pub audio_codec: Option<String>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "fps", skip_serializing_if = "Option::is_none")]
    pub fps: Option<f64>,
    #[serde(rename = "captured_at", skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<String>,
    #[serde(rename = "exposure_time_s", skip_serializing_if = "Option::is_none")]
    pub exposure_time_s: Option<f64>,
    #[serde(rename = "aperture_f_number", skip_serializing_if = "Option::is_none")]
    pub aperture_f_number: Option<f64>,
    #[serde(rename = "iso", skip_serializing_if = "Option::is_none")]
    pub iso: Option<i32>,
    #[serde(rename = "focal_length_mm", skip_serializing_if = "Option::is_none")]
    pub focal_length_mm: Option<f64>,
    #[serde(rename = "camera_make", skip_serializing_if = "Option::is_none")]
    pub camera_make: Option<String>,
    #[serde(rename = "camera_model", skip_serializing_if = "Option::is_none")]
    pub camera_model: Option<String>,
    #[serde(rename = "lens_model", skip_serializing_if = "Option::is_none")]
    pub lens_model: Option<String>,
    #[serde(rename = "orientation", skip_serializing_if = "Option::is_none")]
    pub orientation: Option<i32>,
    #[serde(rename = "bitrate_kbps", skip_serializing_if = "Option::is_none")]
    pub bitrate_kbps: Option<i32>,
    #[serde(rename = "sample_rate_hz", skip_serializing_if = "Option::is_none")]
    pub sample_rate_hz: Option<i32>,
    #[serde(rename = "channel_count", skip_serializing_if = "Option::is_none")]
    pub channel_count: Option<i32>,
    #[serde(rename = "bits_per_sample", skip_serializing_if = "Option::is_none")]
    pub bits_per_sample: Option<i32>,
    #[serde(rename = "rotation_deg", skip_serializing_if = "Option::is_none")]
    pub rotation_deg: Option<i32>,
    #[serde(rename = "timecode_start", skip_serializing_if = "Option::is_none")]
    pub timecode_start: Option<String>,
    #[serde(rename = "pixel_format", skip_serializing_if = "Option::is_none")]
    pub pixel_format: Option<String>,
    #[serde(rename = "color_range", skip_serializing_if = "Option::is_none")]
    pub color_range: Option<String>,
    #[serde(rename = "color_space", skip_serializing_if = "Option::is_none")]
    pub color_space: Option<String>,
    #[serde(rename = "color_transfer", skip_serializing_if = "Option::is_none")]
    pub color_transfer: Option<String>,
    #[serde(rename = "color_primaries", skip_serializing_if = "Option::is_none")]
    pub color_primaries: Option<String>,
    #[serde(rename = "recorder_model", skip_serializing_if = "Option::is_none")]
    pub recorder_model: Option<String>,
    #[serde(rename = "gps_latitude", skip_serializing_if = "Option::is_none")]
    pub gps_latitude: Option<f64>,
    #[serde(rename = "gps_longitude", skip_serializing_if = "Option::is_none")]
    pub gps_longitude: Option<f64>,
    #[serde(rename = "gps_altitude_m", skip_serializing_if = "Option::is_none")]
    pub gps_altitude_m: Option<f64>,
    #[serde(
        rename = "gps_altitude_relative_m",
        skip_serializing_if = "Option::is_none"
    )]
    pub gps_altitude_relative_m: Option<f64>,
    #[serde(
        rename = "gps_altitude_absolute_m",
        skip_serializing_if = "Option::is_none"
    )]
    pub gps_altitude_absolute_m: Option<f64>,
    #[serde(
        rename = "exposure_compensation_ev",
        skip_serializing_if = "Option::is_none"
    )]
    pub exposure_compensation_ev: Option<f64>,
    #[serde(rename = "color_mode", skip_serializing_if = "Option::is_none")]
    pub color_mode: Option<String>,
    #[serde(
        rename = "color_temperature_k",
        skip_serializing_if = "Option::is_none"
    )]
    pub color_temperature_k: Option<i32>,
    #[serde(
        rename = "has_dji_metadata_track",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_dji_metadata_track: Option<bool>,
    #[serde(
        rename = "dji_metadata_track_types",
        skip_serializing_if = "Option::is_none"
    )]
    pub dji_metadata_track_types: Option<Vec<String>>,
}

impl FactsPatch {
    pub fn new() -> FactsPatch {
        FactsPatch {
            duration_ms: None,
            media_format: None,
            video_codec: None,
            audio_codec: None,
            width: None,
            height: None,
            fps: None,
            captured_at: None,
            exposure_time_s: None,
            aperture_f_number: None,
            iso: None,
            focal_length_mm: None,
            camera_make: None,
            camera_model: None,
            lens_model: None,
            orientation: None,
            bitrate_kbps: None,
            sample_rate_hz: None,
            channel_count: None,
            bits_per_sample: None,
            rotation_deg: None,
            timecode_start: None,
            pixel_format: None,
            color_range: None,
            color_space: None,
            color_transfer: None,
            color_primaries: None,
            recorder_model: None,
            gps_latitude: None,
            gps_longitude: None,
            gps_altitude_m: None,
            gps_altitude_relative_m: None,
            gps_altitude_absolute_m: None,
            exposure_compensation_ev: None,
            color_mode: None,
            color_temperature_k: None,
            has_dji_metadata_track: None,
            dji_metadata_track_types: None,
        }
    }
}
