/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureGovernanceRule {
    /// Feature key. Keys listed in `core_v1_global_features` are protected.
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "tier")]
    pub tier: Tier,
    #[serde(rename = "user_can_disable")]
    pub user_can_disable: bool,
    #[serde(rename = "dependencies")]
    pub dependencies: Vec<String>,
    /// Features automatically disabled when this feature is disabled at app/user scope.
    #[serde(rename = "disable_escalation")]
    pub disable_escalation: Vec<String>,
}

impl FeatureGovernanceRule {
    pub fn new(
        key: String,
        tier: Tier,
        user_can_disable: bool,
        dependencies: Vec<String>,
        disable_escalation: Vec<String>,
    ) -> FeatureGovernanceRule {
        FeatureGovernanceRule {
            key,
            tier,
            user_can_disable,
            dependencies,
            disable_escalation,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tier {
    #[serde(rename = "CORE_V1_GLOBAL")]
    CoreV1Global,
    #[serde(rename = "OPTIONAL")]
    Optional,
}

impl Default for Tier {
    fn default() -> Tier {
        Self::CoreV1Global
    }
}
