/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureExplanation {
    #[serde(rename = "effective_value")]
    pub effective_value: bool,
    #[serde(rename = "reason_code", skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<ReasonCode>,
    #[serde(rename = "dependency_key", skip_serializing_if = "Option::is_none")]
    pub dependency_key: Option<String>,
    #[serde(rename = "parent_feature_key", skip_serializing_if = "Option::is_none")]
    pub parent_feature_key: Option<String>,
}

impl FeatureExplanation {
    pub fn new(effective_value: bool) -> FeatureExplanation {
        FeatureExplanation {
            effective_value,
            reason_code: None,
            dependency_key: None,
            parent_feature_key: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReasonCode {
    #[serde(rename = "FEATURE_FLAG_OFF")]
    FeatureFlagOff,
    #[serde(rename = "ADMIN_DISABLED")]
    AdminDisabled,
    #[serde(rename = "USER_OPT_OUT")]
    UserOptOut,
    #[serde(rename = "DEPENDENCY_OFF")]
    DependencyOff,
    #[serde(rename = "DISABLE_ESCALATION")]
    DisableEscalation,
    #[serde(rename = "CORE_PROTECTED")]
    CoreProtected,
    #[serde(rename = "UNSUPPORTED_CONTRACT_VERSION")]
    UnsupportedContractVersion,
}

impl Default for ReasonCode {
    fn default() -> ReasonCode {
        Self::FeatureFlagOff
    }
}
