/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeatureFlags : Runtime flags controlled by Core. Client semantics: missing flag = false, unknown flags are ignored, safe-by-default.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureFlags {
    #[serde(
        rename = "features.decisions.bulk",
        skip_serializing_if = "Option::is_none"
    )]
    pub features_decisions_bulk: Option<bool>,
}

impl FeatureFlags {
    /// Runtime flags controlled by Core. Client semantics: missing flag = false, unknown flags are ignored, safe-by-default.
    pub fn new() -> FeatureFlags {
        FeatureFlags {
            features_decisions_bulk: None,
        }
    }
}
