/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Job : Processing job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Job {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "job_type")]
    pub job_type: JobType,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "asset_uuid")]
    pub asset_uuid: String,
    #[serde(rename = "required_capabilities")]
    pub required_capabilities: Vec<String>,
    #[serde(rename = "claimed_by", skip_serializing_if = "Option::is_none")]
    pub claimed_by: Option<String>,
    #[serde(rename = "lock_token", skip_serializing_if = "Option::is_none")]
    pub lock_token: Option<String>,
    #[serde(rename = "locked_until", skip_serializing_if = "Option::is_none")]
    pub locked_until: Option<String>,
}

impl Job {
    /// Processing job
    pub fn new(
        job_id: String,
        job_type: JobType,
        status: Status,
        asset_uuid: String,
        required_capabilities: Vec<String>,
    ) -> Job {
        Job {
            job_id,
            job_type,
            status,
            asset_uuid,
            required_capabilities,
            claimed_by: None,
            lock_token: None,
            locked_until: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "extract_facts")]
    ExtractFacts,
    #[serde(rename = "generate_proxy")]
    GenerateProxy,
    #[serde(rename = "generate_thumbnails")]
    GenerateThumbnails,
    #[serde(rename = "generate_audio_waveform")]
    GenerateAudioWaveform,
}

impl Default for JobType {
    fn default() -> JobType {
        Self::ExtractFacts
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
