/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobSubmitRequest {
    SubmitExtractFacts(Box<models::SubmitExtractFacts>),
    SubmitDerived(Box<models::SubmitDerived>),
}

impl Default for JobSubmitRequest {
    fn default() -> Self {
        Self::SubmitExtractFacts(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "generate_proxy")]
    GenerateProxy,
    #[serde(rename = "generate_thumbnails")]
    GenerateThumbnails,
    #[serde(rename = "generate_audio_waveform")]
    GenerateAudioWaveform,
}

impl Default for JobType {
    fn default() -> JobType {
        Self::GenerateProxy
    }
}
