/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NonUiClientKind : Allowed client kinds for technical secret-key token minting.
/// Allowed client kinds for technical secret-key token minting.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NonUiClientKind {
    #[serde(rename = "AGENT")]
    Agent,
    #[serde(rename = "MCP")]
    Mcp,
}

impl std::fmt::Display for NonUiClientKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Agent => write!(f, "AGENT"),
            Self::Mcp => write!(f, "MCP"),
        }
    }
}

impl Default for NonUiClientKind {
    fn default() -> NonUiClientKind {
        Self::Agent
    }
}
