/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NonUiClientKind : Allowed client kinds for AGENT technical secret-key token minting.
/// Allowed client kinds for AGENT technical secret-key token minting.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NonUiClientKind {
    #[serde(rename = "AGENT")]
    Agent,
}

impl std::fmt::Display for NonUiClientKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Agent => write!(f, "AGENT"),
        }
    }
}

impl Default for NonUiClientKind {
    fn default() -> NonUiClientKind {
        Self::Agent
    }
}
