/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerPolicy : Runtime server policy returned by Core. `feature_flags` is the source of truth for client feature availability.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerPolicy {
    #[serde(
        rename = "min_poll_interval_seconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_poll_interval_seconds: Option<i32>,
    #[serde(
        rename = "max_parallel_jobs_allowed",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_parallel_jobs_allowed: Option<i32>,
    #[serde(rename = "allowed_job_types", skip_serializing_if = "Option::is_none")]
    pub allowed_job_types: Option<Vec<String>>,
    #[serde(rename = "quiet_hours", skip_serializing_if = "Option::is_none")]
    pub quiet_hours: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "feature_flags")]
    pub feature_flags: models::FeatureFlags,
    /// Latest feature-flags contract version served by Core (SemVer).
    #[serde(rename = "feature_flags_contract_version")]
    pub feature_flags_contract_version: String,
    /// Feature-flags contract versions still accepted by Core for compatibility.
    #[serde(rename = "accepted_feature_flags_contract_versions")]
    pub accepted_feature_flags_contract_versions: Vec<String>,
    /// Feature-flags contract version effectively served to this client request (SemVer).
    #[serde(rename = "effective_feature_flags_contract_version")]
    pub effective_feature_flags_contract_version: String,
    /// STRICT = latest contract served. COMPAT = compatibility profile served (including retired-flag tombstones when required).
    #[serde(rename = "feature_flags_compatibility_mode")]
    pub feature_flags_compatibility_mode: FeatureFlagsCompatibilityMode,
}

impl ServerPolicy {
    /// Runtime server policy returned by Core. `feature_flags` is the source of truth for client feature availability.
    pub fn new(
        feature_flags: models::FeatureFlags,
        feature_flags_contract_version: String,
        accepted_feature_flags_contract_versions: Vec<String>,
        effective_feature_flags_contract_version: String,
        feature_flags_compatibility_mode: FeatureFlagsCompatibilityMode,
    ) -> ServerPolicy {
        ServerPolicy {
            min_poll_interval_seconds: None,
            max_parallel_jobs_allowed: None,
            allowed_job_types: None,
            quiet_hours: None,
            feature_flags,
            feature_flags_contract_version,
            accepted_feature_flags_contract_versions,
            effective_feature_flags_contract_version,
            feature_flags_compatibility_mode,
        }
    }
}
/// STRICT = latest contract served. COMPAT = compatibility profile served (including retired-flag tombstones when required).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeatureFlagsCompatibilityMode {
    #[serde(rename = "STRICT")]
    Strict,
    #[serde(rename = "COMPAT")]
    Compat,
}

impl Default for FeatureFlagsCompatibilityMode {
    fn default() -> FeatureFlagsCompatibilityMode {
        Self::Strict
    }
}
