/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitDerived {
    #[serde(rename = "lock_token")]
    pub lock_token: String,
    #[serde(rename = "job_type")]
    pub job_type: JobType,
    #[serde(rename = "result")]
    pub result: Box<models::SubmitDerivedResult>,
}

impl SubmitDerived {
    pub fn new(
        lock_token: String,
        job_type: JobType,
        result: models::SubmitDerivedResult,
    ) -> SubmitDerived {
        SubmitDerived {
            lock_token,
            job_type,
            result: Box::new(result),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "generate_proxy")]
    GenerateProxy,
    #[serde(rename = "generate_thumbnails")]
    GenerateThumbnails,
    #[serde(rename = "generate_audio_waveform")]
    GenerateAudioWaveform,
}

impl Default for JobType {
    fn default() -> JobType {
        Self::GenerateProxy
    }
}
