/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitDerived {
    #[serde(rename = "lock_token")]
    pub lock_token: String,
    #[serde(rename = "fencing_token")]
    pub fencing_token: i32,
    #[serde(rename = "job_type")]
    pub job_type: JobType,
    #[serde(rename = "result")]
    pub result: Box<models::SubmitDerivedResult>,
}

impl SubmitDerived {
    pub fn new(
        lock_token: String,
        fencing_token: i32,
        job_type: JobType,
        result: models::SubmitDerivedResult,
    ) -> SubmitDerived {
        SubmitDerived {
            lock_token,
            fencing_token,
            job_type,
            result: Box::new(result),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "generate_preview")]
    GeneratePreview,
    #[serde(rename = "generate_thumbnails")]
    GenerateThumbnails,
    #[serde(rename = "generate_audio_waveform")]
    GenerateAudioWaveform,
}

impl Default for JobType {
    fn default() -> JobType {
        Self::GeneratePreview
    }
}
