/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TechnicalClientKind : Allowed client kinds for technical bearer tokens.
/// Allowed client kinds for technical bearer tokens.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TechnicalClientKind {
    #[serde(rename = "AGENT")]
    Agent,
    #[serde(rename = "MCP")]
    Mcp,

}

impl std::fmt::Display for TechnicalClientKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Agent => write!(f, "AGENT"),
            Self::Mcp => write!(f, "MCP"),
        }
    }
}

impl Default for TechnicalClientKind {
    fn default() -> TechnicalClientKind {
        Self::Agent
    }
}

