/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TranscriptPatch : Pre-release transcript merge patch. Accepted only when `features.ai.transcribe_audio` is effectively enabled; outside v1 conformance scope until validated v1.1+ rollout.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscriptPatch {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "text_preview", skip_serializing_if = "Option::is_none")]
    pub text_preview: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl TranscriptPatch {
    /// Pre-release transcript merge patch. Accepted only when `features.ai.transcribe_audio` is effectively enabled; outside v1 conformance scope until validated v1.1+ rollout.
    pub fn new() -> TranscriptPatch {
        TranscriptPatch {
            status: None,
            text: None,
            text_preview: None,
            language: None,
            updated_at: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "DONE")]
    Done,
    #[serde(rename = "FAILED")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::None
    }
}
