/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core (minor features up to v1.1).  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. AI-powered features are planned for v1.1+ and are out of v1 conformance scope.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserFeaturesResponse {
    /// User-level feature switches. Only non-core features can be disabled at user scope. Missing key is interpreted as `true` (migration-safe default).
    #[serde(rename = "user_feature_enabled")]
    pub user_feature_enabled: std::collections::HashMap<String, bool>,
    /// Effective availability after all gates (`feature_flags`, `app_feature_enabled`, `user_feature_enabled`, dependencies). Evaluation order is strict: feature_flags -> app_feature_enabled -> user_feature_enabled -> dependency/escalation rules.
    #[serde(rename = "effective_feature_enabled")]
    pub effective_feature_enabled: std::collections::HashMap<String, bool>,
    #[serde(rename = "feature_governance")]
    pub feature_governance: Vec<models::FeatureGovernanceRule>,
    /// Canonical list of non-disableable v1 global core feature keys.
    #[serde(rename = "core_v1_global_features")]
    pub core_v1_global_features: Vec<models::CoreV1GlobalFeatureKey>,
}

impl UserFeaturesResponse {
    pub fn new(
        user_feature_enabled: std::collections::HashMap<String, bool>,
        effective_feature_enabled: std::collections::HashMap<String, bool>,
        feature_governance: Vec<models::FeatureGovernanceRule>,
        core_v1_global_features: Vec<models::CoreV1GlobalFeatureKey>,
    ) -> UserFeaturesResponse {
        UserFeaturesResponse {
            user_feature_enabled,
            effective_feature_enabled,
            feature_governance,
            core_v1_global_features,
        }
    }
}
