/*
 * Retaia Core API
 *
 * Normative OpenAPI v1 for Retaia Core.  This API coordinates assets, processing jobs and agents. Agents are non-reliable by design. Jobs may remain pending indefinitely if no compatible agent is available. Product maturity labels such as beta or release candidate are independent from this API major version. AI-powered features are planned for v1.1+ and are out of v1 conformance scope. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebAuthnAuthenticateVerifyRequest {
    #[serde(rename = "credential")]
    pub credential: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "client_kind", skip_serializing_if = "Option::is_none")]
    pub client_kind: Option<models::ClientKind>,
}

impl WebAuthnAuthenticateVerifyRequest {
    pub fn new(credential: std::collections::HashMap<String, serde_json::Value>) -> WebAuthnAuthenticateVerifyRequest {
        WebAuthnAuthenticateVerifyRequest {
            credential,
            client_id: None,
            client_kind: None,
        }
    }
}

